Auth_Api: /v1/api/auth
Login: /login
Test: /test
Logout: /logout
AccessToken: /getAccessToken
Booking_Api: /v1/api/booking
ViewSlots: /viewslots/{id}
Calender: /meetingsbyyear/{year}
Rooms_Api: /v1/api/rooms
RoomsDisplay: /display
RoomsDisplayById:  /displaybyId/{id}
User_Api: /v1/api
UserDetails: /details
Feedback_Api: /v1/api/feature/feedback
SaveFeedback: /savefeedback
Last4Feedback: /get/feedback/lastfouruser
FeedbackDate: /get/feedback/date
Attendees_Api: /v1/api/user/attendees
InternalAttendees: /internalattendees
MeetingCategory_Api: /v1/api/user
CategoriesDisplay: /categories
UserMeeting_Api: /v1/api/user/meeting
BookMeeting-User: /bookmeeting
EditMeeting-User: /editmeeting/{id}
UserDashboard-User: /getuserdashboardmeeting/date/{date}
CompletedMeeting-User: /get/completedmeeting
UpcomingMeeting-User: /get/upcomingmeeting/{status}
WithdrawMeeting-User: /withdrawmeeting/{id}
Facility_Api: /v1/api/admin/facilities
FacilityDisplay: /display
MeetingCategoryAdmin_Api: /v1/api/admin/meetingCategory
AddApi: /add
RoomsAdmin_Api: /v1/api/admin/rooms
AdminMeeting_Api: /v1/api/admin/meeting
BlockMeeting-Admin: /block
UnBlockMeeting-Admin: /unblockbyid
UpcomingMeetingHost-Admin: /upcomingmeetingsbyhost
Request-Admin: /requests
Unblock-Admin: /unblock
UpcomingMeeting-Admin: /upcomingmeetings
History-Admin: /history
Accept-Admin: /accept/{id}
Reject-Admin: /reject/{id}